conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls')),
]

contacts/urls.py
from django.urls import path
from .views import *
 
app_name = 'contacts'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('individual_input/', IndividualContactInput.as_view(), name='individual_input'),
    path('individual_confirm/', IndividualContactConfirm.as_view(), name='individual_confirm'),
    path('individual_create/', IndividualContactCreate.as_view(), name='individual_create'),
    path('corporate_input/', CorporateContactInput.as_view(), name='corporate_input'),
    path('corporate_confirm/', CorporateContactConfirm.as_view(), name='corporate_confirm'),
    path('corporate_create/', CorporateContactCreate.as_view(), name='corporate_create'),
    path('form_send_complete/', FormSendComplete.as_view(), name='form_send_complete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
  is_received_email = models.BooleanField(verbose_name='お問い合わせメールを受け取るか', default=True)
  
  @staticmethod
  def get_users_emailed():
    return CustomUser.objects.filter(is_received_email = True)
  
  @staticmethod
  def email_users(users, subject, message, from_email=True):
    for user in users:
      user.email_user(subject, message, from_email)

contacts/models.py
from django.db import models
from django.template.loader import get_template
from accounts.models import CustomUser

# Create your models here.
def contact_type_handler(contact_type):
  if not isinstance(contact_type, str):
    raise TypeError("contact_type must be str type")
  
  if contact_type not in ('individual', 'corporate'):
    raise ValueError("contact_type must be 'individual' or 'corporate'")

class BaseContact(models.Model):
  datetime = models.DateTimeField(verbose_name='お問い合わせ日時', auto_now_add=True)
  content = models.TextField(verbose_name='お問い合わせ内容', blank=False)
  email = models.EmailField(verbose_name='メールアドレス', blank=False)
  
  class Meta:
    abstract = True
    
  def __str__(self):
    return self.content
  
  @staticmethod
  def base_email_users(form, from_email, contact_type):
    contact_type_handler(contact_type)
    context = {
      'form': form,
    }
    subject_template = get_template('contacts/email/{}_subject.txt'.format(contact_type))
    subject = subject_template.render(context)
    
    message_template = get_template('contacts/email/{}_message.txt'.format(contact_type))
    message = message_template.render(context)
    
    CustomUser.email_users(CustomUser.get_users_emailed(), subject, message, from_email)
    
class IndividualContact(BaseContact):
  fullname = models.CharField(verbose_name='氏名', blank=False, max_length=30)
  kana = models.CharField(verbose_name='フリガナ', blank=False, max_length=60)

  @staticmethod
  def email_users(form, from_email):
    BaseContact.base_email_users(form, from_email, 'individual')


class CorporateContact(BaseContact):
  corporate_name = models.CharField(verbose_name='企業名', blank=False, max_length=30)
  pic_name = models.CharField(verbose_name='担当者名', blank=False, max_length=30)
  phonenumber = models.CharField(verbose_name='電話番号', blank=False, max_length=16)

  @staticmethod
  def email_users(form, from_email):
    BaseContact.base_email_users(form, from_email, 'corporate')

contacts/forms.py
from django.forms import ModelForm
from contacts.models import CorporateContact, IndividualContact
 
class IndividualContactForm(ModelForm):
    class Meta:
        model = IndividualContact
        fields = '__all__'
 
class CorporateContactForm(ModelForm):
    class Meta:
        model = CorporateContact
        fields = '__all__'

accounts/views.py
from django.shortcuts import render

# Create your views here.

contacts/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import render
from .forms import CorporateContactForm, IndividualContactForm
from .models import IndividualContact, CorporateContact

class Home(generic.TemplateView):
    template_name = 'contacts/index.html'


class IndividualContactInput(generic.FormView):
    template_name = 'contacts/individual_contact_input.html'
    form_class = IndividualContactForm

    def form_valid(self, form):
        return render(self.request, IndividualContactInput.template_name, {'form': form})


class IndividualContactConfirm(generic.FormView):
    form_class = IndividualContactForm

    def form_valid(self, form):
        return render(self.request, 'contacts/individual_contact_confirm.html', {'form': form})

    def form_invalid(self, form):
        return render(self.request, IndividualContactInput.template_name, {'form': form})


class IndividualContactCreate(generic.CreateView):
    form_class = IndividualContactForm
    success_url = reverse_lazy('contacts:form_send_complete')

    def form_invalid(self, form):
        return render(self.request, IndividualContactInput.template_name, {'form': form})

    def form_valid(self, form):
        IndividualContact.email_users(form, 'sample@internetacademy.co.jp')
        return super().form_valid(form)


class CorporateContactInput(generic.FormView):
    template_name = 'contacts/corporate_contact_input.html'
    form_class = CorporateContactForm

    def form_valid(self, form):
        return render(self.request, CorporateContactInput.template_name, {'form': form})


class CorporateContactConfirm(generic.FormView):
    form_class = CorporateContactForm

    def form_valid(self, form):
        return render(self.request, 'contacts/corporate_contact_confirm.html', {'form': form})

    def form_invalid(self, form):
        return render(self.request, CorporateContactInput.template_name, {'form': form})


class CorporateContactCreate(generic.CreateView):
    form_class = CorporateContactForm
    success_url = reverse_lazy('contacts:form_send_complete')

    def form_invalid(self, form):
        return render(self.request, CorporateContactInput.template_name, {'form': form})

    def form_valid(self, form):
        CorporateContact.email_users(form, 'sample@internetacademy.co.jp')
        return super().form_valid(form)


class FormSendComplete(generic.TemplateView):
    template_name = 'contacts/form_send_complete.html'

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Python 講座{% endblock %}</title>
</head>
<main>
    {% block content %}
    {% endblock %}
</main>
</html>

templates/contacts/corporate_contact_confirm.html
{% extends "base.html" %}
{% block title %}corporate contact form confirm{% endblock %}
 
{% block content %}
    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field.value }}
        </div>
    {% endfor %}
 
    <form action="{% url 'contacts:corporate_input' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
    <hr>
    <form action="{% url 'contacts:corporate_create' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
{% endblock %}

templates/contacts/corporate_contact_input.html
{% extends 'base.html' %}
 
{% block title %}corporate contact form input{% endblock %}
{% block content %}
    <form action="{% url 'contacts:corporate_confirm' %}" method="POST">
         
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}

templates/contacts/form_send_complete.html
{% extends 'base.html' %}
{% block content %}
    <p>フォームの送信が完了しました</p>
{% endblock %}

templates/contacts/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>お問い合わせフォーム</h1>
<a href="{% url 'contacts:individual_input' %}"><p>個人の方はこちら</p></a>
<a href="{% url 'contacts:corporate_input' %}"><p>法人の方はこちら</p></a>
{% endblock %}

templates/contacts/individual_contact_confirm.html
{% extends "base.html" %}
{% block title %}individual contact form confirm{% endblock %}
 
{% block content %}
    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field.value }}
        </div>
    {% endfor %}
 
    <form action="{% url 'contacts:individual_input' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">戻る</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
    <hr>
    <form action="{% url 'contacts:individual_create' %}" method="POST">
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
        {% for field in form %}{{ field.as_hidden }}{% endfor %}
        {% csrf_token %}
    </form>
{% endblock %}

templates/contacts/individual_contact_input.html
{% extends 'base.html' %}
 
{% block title %}individual contact form input{% endblock %}
{% block content %}
    <form action="{% url 'contacts:individual_confirm' %}" method="POST">
         
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">送信</button>
    </form>
{% endblock %}